\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename now-playing.info
@settitle now-playing.el User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* now-playing: (now-playing). A “Now Playing” interface for the macOS Music app.
@end direntry

@finalout
@titlepage
@title now-playing.el User Guide
@subtitle for version 0.9.5-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top now-playing.el User Guide

Version: 0.9.5-rc.1

Copyright © 2026 @w{Charles Y. Choi}

@image{images/now-playing-screenshot,,,,png}

@strong{now-playing.el} is an Emacs @uref{https://docs.magit.vc/transient/, Transient} interface for the macOS @uref{https://en.wikipedia.org/wiki/Music_%28app%29, Music app}. @strong{now-playing.el} lets you control the @strong{Music app} with the following commands:

@itemize
@item
Pause/Play (@code{SPC})
@item
Previous (@code{p}) and Next (@code{n}) Track
@item
Open (launch) Music app (@code{o})
@item
Increase (@code{<up>}) and Decrease (@code{<down>}) volume
@item
Refresh current track (@code{r})
@end itemize

@strong{now-playing.el} is an ancillary interface to the @strong{Music app}@comma{} providing only a subset of controls to it and no more.

If you enjoy using @strong{now-playing.el}@comma{} please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Features::
* Requirements::
* Install::
* Commands::
* Feedback & Discussion::
* Sponsorship::
* About::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Commands

* Polling the Current Track::

@end detailmenu
@end menu

@node Features
@chapter Features

@cindex Features

@itemize
@item
Transient menu interface to control @strong{Music app}.

@code{M-x} @code{now-playing-tmenu}

@item
Display the current playing track in the mini-buffer.

@code{M-x} @code{now-playing-current-track}

@item
Periodically poll the @strong{Music app} to display the current track in the mini-buffer.

@code{M-x} @code{now-playing-start-polling-current-track}

When polling is turned on@comma{} an in-memory log is kept in the special buffer @emph{@strong{now playing log}}. It can be opened with the command @code{now-playing-find-log}.

Polling can be stopped with the command @code{now-playing-cancel-polling}.

@item
Theme support for GUI and TTY display.

By default @strong{now-playing.el} uses @uref{https://developer.apple.com/sf-symbols/, SF Symbols} for icons. This can be reconfigured for Unicode or text display only.

@item
Uses Emacs @code{ns-do-applescript} to directly call AppleScript for performance.
@end itemize

@node Requirements
@chapter Requirements

@cindex Requirements

@strong{now-playing.el} requires GNU Emacs 30.1+ running on macOS 13 (Ventura) or greater.  NS support is recommended for optimal performance.

@node Install
@chapter Install

@cindex Install

@strong{now-playing.el} is available to install from MELPA (TBD).

For manual installation@comma{} ensure that  @code{now-playing.el} is available in the Emacs  @code{load-path} variable.

@strong{now-playing.el} by default requires your Emacs session to load the macOS SF Symbols font. Use the convenience command @code{now-playing-init} to setup both SF Symbols and to globally set your keybinding preference to the Transient menu @code{now-playing-tmenu}.

Interactively run @code{M-x now-playing-init} or add the following line to your Emacs initialization file:

@lisp
(now-playing-init "<f14>")
@end lisp

Alternately@comma{} a direct setting of your keybinding preference to @code{now-playing-tmenu} can be done as follows:

@lisp
(keymap-global-set "<f14>" #'now-playing-tmenu)
@end lisp

@node Commands
@chapter Commands

@cindex Commands

The primary interface for @strong{now-playing.el} is the Transient menu @code{now-playing-tmenu}. It can be invoked via @code{execute-extended-command} @kbd{M-x}.

Listed below are commands to both control or get current information from the Music app.

@table @asis
@item now-playing-tmenu
Transient menu for @strong{now-playing.el}.
@vindex now-playing-tmenu

@image{images/now-playing-screenshot,,,,png}

The following commands are provided:

@itemize
@item
Pause/Play (@code{SPC})
@item
Previous (@code{p}) and Next (@code{n}) Track
@item
Open (launch) Music app (@code{o})
@item
Increase (@code{<up>}) and Decrease (@code{<down>}) volume
@item
Refresh current track (@code{r})
@item
Settings (@code{@comma{}})
@end itemize

@item now-playing-set-state
Set Music app playback state.
@vindex now-playing-set-state

@item now-playing-play
Play Music app.
@vindex now-playing-play

Note if there is no current track@comma{} this AppleScript command will not succeed. If this occurs@comma{} switch to the Music app to directly select a track to play.

@item now-playing-pause
Pause Music app.
@vindex now-playing-pause

@item now-playing-playpause
Toggle play or pause Music app.
@vindex now-playing-playpause

Note if there is no current track@comma{} this AppleScript command will not succeed. If this occurs@comma{} switch to the Music app to directly select a track to play.

@item now-playing-stop
Stop Music app.
@vindex now-playing-stop

Note this command will deselect the current track in the Music app@comma{} making the commands @code{now-playing-play} and @code{now-playing-playpause} ineffective. If this occurs@comma{} switch to the Music app and select a track to resume expected behavior.

@item now-playing-next-track
Next track Music app.
@vindex now-playing-next-track

Note if this command is called when on the last track of the playlist or album will deselect the current track.

@item now-playing-previous-track
Previous track Music app.
@vindex now-playing-previous-track

Note if this command is called when on the first track of the playlist or album will deselect the current track.

@item now-playing-get-volume
Get Music app sound volume.
@vindex now-playing-get-volume

@item now-playing-set-volume
Set Music app sound volume to ARG@.
@vindex now-playing-set-volume

@item now-playing-increase-volume
Increase Music app sound volume.
@vindex now-playing-increase-volume

@item now-playing-decrease-volume
Decrease Music app sound volume.
@vindex now-playing-decrease-volume

@item now-playing-current-track
Get current track on Music app.
@vindex now-playing-current-track

@item now-playing-launch-music
Launch Music app.
@vindex now-playing-launch-music
@end table

@subsubheading Command Variables

The following customizable variables can be changed to preference:

@table @asis
@item now-playing-volume-delta
Change increment for sound volume (default 5).
@vindex now-playing-volume-delta

@item now-playing-dismiss-menu-for-playpause
If non-nil@comma{} then toggling pause/play will dismiss the Transient menu
@code{now-playing-tmenu}.
@vindex now-playing-dismiss-menu-for-playpause

@item now-playing-menu-theme
Theme for menu descriptions.
@vindex now-playing-menu-theme

Customize this variable to a theme of preference:

@itemize
@item
SF Symbols (@code{:sfsymbols})
@item
Unicode (@code{:unicode})
@item
Text (@code{:text})
@end itemize

Both Unicode and Text allow for usage on TTY frames on systems that do not support SF Symbols.
@end table

@menu
* Polling the Current Track::
@end menu

@node Polling the Current Track
@section Polling the Current Track

@cindex Polling the Current Track

@strong{now-playing.el} provides the capability to periodically log the current track into the special buffer @code{✱now playing log✱}.  The commands that control polling are listed below:

@table @asis
@item now-playing-start-polling-current-track
Poll current track with period @code{now-playing-poll-interval}.
@vindex now-playing-start-polling-current-track

@item now-playing-cancel-polling
Cancel poll timer.
@vindex now-playing-cancel-polling

@item now-playing-find-log
Find @code{✱now playing log✱} buffer.
@vindex now-playing-find-log

@item now-playing-is-polling-p
Predicate if logging the current track.
@vindex now-playing-is-polling-p
@end table


@subsubheading Polling Variable

Use the following variable to control sound volume changes.

@table @asis
@item now-playing-poll-interval
Poll interval (or period) in seconds
@vindex now-playing-poll-interval
@end table

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about @strong{now-playing.el} to the @uref{https://github.com/kickingvegas/now-playing/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using @strong{now-playing.el}@comma{} please join the @uref{https://github.com/kickingvegas/now-playing/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

If you enjoy using @strong{now-playing.el}@comma{} please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@node About
@chapter About

@cindex About

@uref{https://github.com/kickingvegas/now-playing, now-playing.el} was conceived and crafted by Charles Choi in San Francisco@comma{} California.

Thank you for using @strong{now-playing.el}.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks to developers responsible for providing @code{ns-do-applescript} in NS Emacs.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
